services:
  - type: web
    name: price-scrapper
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    build:
      cwd: backend
    source:
      repo: https://github.com/shingchan95/price-scrapper
      branch: main
      autoDeploy: true
